### ISSUE TITLE
Auto alignment of Rasor

### ISSUE THREAD

**Issue by Relm-Arrowny** [DiamondLightSource/sm-bluesky#15]
### Goals
- [ ] To be able to run a plan in bluesky(possibly using blueapi) to automatically align i10 Rasor.
        e.g. Type in command line RE.(alignRasor) or blueapi controller run alignRasor and the beamline will be magically aligned.
- [ ] It must not interference with GDA and can be turn off after alignment.

### Tasks
- [x] Deploy bluesky in a container on one of the WS on i10. 
- [x] Make motors into bluesky read/writable devices. DiamondLightSource/i10-bluesky#4 
- [x] Make photo diode into readable devices. 
- [ ] Create plans with all the required logic DiamondLightSource/sm-bluesky#9 
- [ ] Create beam to pin plan.
